SIM = verilator
VERILATOR_EXTRA_ARGS += -sv
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += /home/homew/riscv-cpu/riscv-cpu/src/alu.sv

TOPLEVEL = alu
MODULE = test_alu

include $(shell cocotb-config --makefiles)/Makefile.sim