SIM = verilator
VERILATOR_EXTRA_ARGS += -sv
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += /home/homew/riscv-cpu/riscv-cpu/src/control.sv

TOPLEVEL = control
MODULE = test_control

include $(shell cocotb-config --makefiles)/Makefile.sim