SIM = verilator
VERILATOR_EXTRA_ARGS += -sv
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += /home/homew/riscv-cpu/riscv-cpu/src/signext.sv

TOPLEVEL = signext
MODULE = test_signext

include $(shell cocotb-config --makefiles)/Makefile.sim