SIM = verilator
VERILATOR_EXTRA_ARGS += -sv
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += /home/homew/riscv-cpu/riscv-cpu/src/regfile.sv

TOPLEVEL = regfile
MODULE = test_regfile

include $(shell cocotb-config --makefiles)/Makefile.sim