SIM = verilator
VERILATOR_EXTRA_ARGS += -sv
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += /home/homew/riscv-cpu/riscv-cpu/src/memory.sv

TOPLEVEL = memory
MODULE = test_memory

include $(shell cocotb-config --makefiles)/Makefile.sim